### ISSUE TITLE
ImportError: cannot import name 'cpu' from partially initialized module 'encoding' (most likely due to a circular import)

### ISSUE THREAD

**Issue by Coobiw** [zhanghang1989/PyTorch-Encoding#424]
ImportError: cannot import name 'cpu' from partially initialized module 'encoding' (most likely due to a circular import)

>>> torch.__version__
'2.0.0+cu117'

>>> torch.version.cuda
'11.7'

Actually, before I install pytorch-encoding, I install torch=1.9.1+cu111 torchvison=0.10.1+cu111

after install pytorch-encoding, it changed.

**Comment by HustQBW** [comment]
Sorry,the version change is because I install pytorch-lightning. Now I have turn back to torch=1.9.1+cu111 torchvison=0.10.1+cu111. 
Unfortunately, after 

`pip uninstall torch-encoding`

I run : 

`python setup.py install`

and get an error:

`RuntimeError: Error compiling objects for extension`

Thanks for your sincere answer.

**Comment by HustQBW** [comment]
I solve this problem by pip, just run:

`pip install torch-encoding`.

Really embarrassing.
